### PR TITLE
Fixed #4, except for lib/packets/setup/setStation.js

### LINKED ISSUE #4: Remove any mentions of stations
'Stations' can mean two things: a player station (aka console) or a station to be docked at (a base). Any reference to 'station' should be removed and replaced with either console or base.

### PR DESCRIPTION
**Pull request by somebody1234**
Fixes https://github.com/mrfishie/node-artemis/issues/4
It's probably going to throw a lot of errors

### CODE REVIEW

**Comment by mrfishie** [comment]
Get it to a point where it doesn't and I'll merge ;)
I can set you as the assignee for that issue if you want

**Comment by somebody1234** [comment]
I don't think I can test it.

**Comment by mrfishie** [comment]
Have you installed [Node](https://nodejs.org/download/) and ran the commands in the [quick-start guide](https://github.com/mrfishie/node-artemis)?

**Comment by somebody1234** [comment]
I was going to do that, until I read
**If you do not have the required data files, node-artemis will not be able to run. As a result, you cannot (and definitely should not!) use node-artemis without owning the Artemis game.**

**Comment by mrfishie** [comment]
Ah, of course. The server will still start, though, so you should be able to just run the command and see if it comes up with any errors (apart from the one saying it can't find the vesselData.xml file). And also, the command `npm start` currently is configured to use [io.js](https://iojs.org/) instead of Node, so you can either install io.js or run `node bin/artemis` instead.

**Comment by somebody1234** [comment]
Okay. Also, what does setStation refer to?

**Comment by mrfishie** [comment]
The packet? That refers to a client selecting a **console**.

**Comment by somebody1234** [comment]
It works now (apart from the vesselData.xml)

**Comment by mrfishie** [comment]
Its not working for me yet... I'm getting these errors: (after trying to connect with a client)
- cannot read property 'weapons' of undefined (in lib/entities/weapons:17:32)
- cannot read property 'stations' of undefined (in lib/states/game:123:57)
- cannot read property 'driveType' of undefined (in lib/packets/setup/allShipSettings.js:10:30)
  Looks like there is still some more to do...

**Comment by mrfishie** [comment]
Remember that most packets have a pack _and_ unpack function, and you will probably need to change both (for example in setConsole)

**Comment by somebody1234** [comment]
What does server.config.lobby.stations refer to?

**Comment by somebody1234** [comment]
Should be fixed now

**Comment by mrfishie** [comment]
Another error sorry... ReferenceError: consoleList is not defined (in lib/states/game.js:124:37).  
I think that reference to `consoleList` should be `consoleListOriginal`

**Comment by somebody1234** [comment]
Fixed.

**Comment by mrfishie** [comment]
Awesome, thanks!

**Pull request merged**
